name: Build release npm package, Reanimated 2

on:
  workflow_dispatch:

jobs:
  call-build-workflow-rea-v2:
    uses: ./.github/workflows/build-npm-package-action.yml
    with:
      version: release
      ref: ${{ github.ref }}
      upload_binaries: true
      